---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maven
  name: maven
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - image: duniaalk/kaniko-maven
        imagePullPolicy: Always
        name: maven
